### ISSUE TITLE
iOS 11.4 simulator crash

### ISSUE THREAD

**Issue by jaumard** [dart-flitter/flutter_webview_plugin#129]
Just want to try this plugin but have: 

```
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      FlutterWebviewPlugin.close (package:flutter_webview_plugin/src/base.dart:121:30)
#2      _WebviewScaffoldState.initState (package:flutter_webview_plugin/src/webview_scaffold.dart:51:22)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#9      ComponentElement._firstBuild (package:<…>
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:110:20)
<asynchronous suspension>
#2      _WebviewScaffoldState.build (package:flutter_webview_plugin/src/webview_scaffold.dart:64:24)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#9      Elemen<…>
```

Works on my Android device.

**Comment by lejard-h** [comment]
Hi, try a `flutter packages upgrade` if it still don't work can you post your `flutter doctor` result ?

**Comment by manondidi** [comment]
same problem,did you fix it?

**Comment by slightfoot** [comment]
You need to run flutter clean and then build its because the Pod for the plugin has not been included as part of the build process. Running this https://gist.github.com/jeroen-meijer/bc62dcc74e10e745be7b5790cf74edf0 should resolve it.
