### ISSUE TITLE
This plugin do not work on Android

### ISSUE THREAD

**Issue by hahafather007** [dart-flitter/flutter_webview_plugin#153]
I have tried kinds of android version, from 5.0 to 9.0, it's all throw this exception. But it's work well on IOS.(Plugin version is 0.2.1+1)
```
E/flutter (28731): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (28731): PlatformException(error, android.webkit.WebView cannot be cast to com.flutter_webview_plugin.ObservableWebView, null)
E/flutter (28731): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter (28731): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (28731): <asynchronous suspension>
E/flutter (28731): #2      FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:137:20)
E/flutter (28731): <asynchronous suspension>
E/flutter (28731): #3      _WebviewScaffoldState.build (package:flutter_webview_plugin/src/webview_scaffold.dart:71:24)
E/flutter (28731): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
E/flutter (28731): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
E/flutter (28731): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (28731): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
E/flutter (28731): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
E/flutter (28731): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
E/flutter (28731): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
E/flutter (28731): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (28731): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
E/flutter (28731): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
E/flutter (28731): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
E/flutter (28731): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
E/flutter (28731): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (28731): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
E/flutter (28731): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
E/flutter (28731): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
E/flutter (28731): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
E/flutter (28731): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
E/flutter (28731): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
E/flutter (28731): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
E/flutter (28731): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
E/flutter (28731): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
E/flutter (28731): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (28731): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
E/flutter (28731): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
E/flutter (28731): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
```
And my flutter doctor like this:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by hahafather007** [comment]
Is there anyone to help me to solve this problem?

**Comment by hahafather007** [comment]
#150

**Comment by lejard-h** [comment]
duplicate https://github.com/dart-flitter/flutter_webview_plugin/issues/152
