### ISSUE TITLE
Webview dont load for Android with new flutter version

### ISSUE THREAD

**Issue by MilloshFey** [dart-flitter/flutter_webview_plugin#973]
## System info

Issue occurs on: Android
Plugin version: 0.4.0
Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 13.6.1 22G313 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    ! CocoaPods 1.11.2 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)
[✓] Network resources
```

## Steps to Reproduce

I upgraded Flutter to the latest stable version (Flutter 3.24.0 • channel stable).
Then created a new default flutter project and installed the plugin.

When I click to open the webview (any of them) I get the error:

E/flutter (15045): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
E/flutter (15045): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (15045): <asynchronous suspension>
E/flutter (15045): #1      FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:217:5)
E/flutter (15045): <asynchronous suspension>
E/flutter (15045): 

It works fine with IOS.
commands like 'flutter clean run' or deleting pubspec.lock didn't work. 

## Logs

```
```

```
```

```
```

**Comment by manenga** [comment]
Feel free to use my [updated version using android v2 embeddings](https://pub.dev/packages/flutter_webview_plugin_android_v2).

**Comment by 211277729** [comment]
> 请随意使用[我的更新版本，使用 android v2 嵌入](https://pub.dev/packages/flutter_webview_plugin_android_v2)。

Hello, when performing ios packaging on the package you provided, the following error is reported

error
[!] No podspec found for `flutter_webview_plugin_android_v2` in `.symlinks/plugins/flutter_webview_plugin_android_v2/ios`

**Comment by 211277729** [comment]
> 请随意使用[我的更新版本，使用 android v2 嵌入](https://pub.dev/packages/flutter_webview_plugin_android_v2)。

Hello, I also found another problem with your package. At present, there is a scanning function in the web page embedded in my APP. Your package will report an error without permission, Uncaught (in promise) NotAllowedError: Permission denied, before this I used flutter_webview_plugin 4.0.0 to stop maintenance, please take a look
